# Configures the local profile to be used in case no other is specified on bootstrap
spring:
  profiles:
    active: local

---
# Snippet configuration that teaches me how to use on-profile on a single application properties file
#  config:
#    activate:
#      on-profile:
#        - local
